name: tester-dclane
base: core20 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: test of using layouts
description: |
    don't care for this

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  tester-dclane:
    # See 'snapcraft plugins'
    plugin: make
    source: https://github.com/dclane-code/tester-dclane.git
    stage-packages:
    - ca-certificates
    - ca-certificates-java
    - openjdk-17-jdk

apps:
  tester-dclane:
    command: tester
    plugs:
    - home #for the abilty to open files in /home/dclane/
