name: tester-dclane
base: core20 # the base snap is the execution environment for this snap
version: '0.3' # just for humans, typically '1.2+git' or '1.3.2'
summary: test various things with a published snap
description: |
    don't care for this

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - amd64

parts:
  tester-dclane:
    # See 'snapcraft plugins'
    plugin: make
    source: src/

  magic-value:
    plugin: dump
    source: .

apps:
  tester-dclane:
    command: tester
    plugs:
    - home #for the abilty to open files in /home/dclane/
    - network-control
    - docker

  magic-value:
    command: magic.sh

